<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>18759d1a-c09a-45cb-8c8c-361583dd19e1</UserSecretsId>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\ErrorTriage\ErrorTriageDashboard_old.cshtml" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\buttons.html5.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\buttons.print.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\datatables.buttons.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\jquery.dataTables.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\jszip.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\pdfmake.min.js" />
    <Content Remove="wwwroot\assets\vendor\libs\datatables\vfs_fonts.js" />
    <Content Remove="wwwroot\FormTemplates\1094-B_2025_2025-Final-1094-B Form.pdf" />
    <Content Remove="wwwroot\FormTemplates\1094-C_2025_2025-Final-1094-C Form.pdf" />
    <Content Remove="wwwroot\FormTemplates\1095-B_2025_2025-Final-1095-B Form.pdf" />
    <Content Remove="wwwroot\FormTemplates\1095-C_2025_2025-Final-1095-C Form.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="EPPlus" Version="7.3.2" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.0" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACA360.BusinessLogic\ACA360.BusinessLogic.csproj" />
    <ProjectReference Include="..\ACA360.Data\ACA360.Data.csproj" />
    <ProjectReference Include="..\ACA360.Logging\ACA360.Logging.csproj" />
    <ProjectReference Include="..\ACA360.Repositories\ACA360.Repositories.csproj" />
    <ProjectReference Include="..\ACA360.Security\ACA360.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AppStart\" />
    <Folder Include="Data\" />
    <Folder Include="GeneratedReports\MultiEmployerBatches\" />
    <Folder Include="wwwroot\images\Excel\" />
    <Folder Include="wwwroot\lib\bootstrap\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\css\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\lib\jquery-validation\" />
    <Folder Include="wwwroot\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\lib\jquery\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
    <Folder Include="wwwroot\assets\vendor\libs\select2\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\vendor\libs\datatables\buttons.html5.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\buttons.print.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\datatables.buttons.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\jquery.datatables.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\jszip.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\pdfmake.min.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables\vfs_fonts.js" />
    <None Include="wwwroot\FormTemplates\1094-B_2025_2025-Final-1094-B Form.pdf" />
    <None Include="wwwroot\FormTemplates\1094-C_2025_2025-Final-1094-C Form.pdf" />
    <None Include="wwwroot\FormTemplates\1095-B_2025_2025-Final-1095-B Form.pdf" />
    <None Include="wwwroot\FormTemplates\1095-C_2025_2025-Final-1095-C Form.pdf" />
  </ItemGroup>

</Project>
