<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACA360.BusinessLogic\ACA360.BusinessLogic.csproj" />
    <ProjectReference Include="..\ACA360.Logging\ACA360.Logging.csproj" />
    <ProjectReference Include="..\ACA360.Repositories\ACA360.Repositories.csproj" />
  </ItemGroup>

</Project>
